// Build the GitHub Pages demo (demo/ → demo/dist/).
//
// 产物是纯静态单页：一个 main.js（bundle 了 src/、elkjs、bpmn-moddle、bpmn-js 和全部
// fixture JSON）+ index.html/style.css + bpmn-js 的 css 资产。elk-worker.min.js 以源码字符串
// 内嵌（demo/generated/elk-worker-source.ts），运行时经 provideBrowserElkWorkerSource 注入。
// generated/ 与 dist/ 均为构建产物，不入库。

import { cp, mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { join } from 'node:path';

const root = join(import.meta.dir, '..');
const nodeRequire = createRequire(import.meta.url);

const generatedDir = join(root, 'demo', 'generated');
const distDir = join(root, 'demo', 'dist');
await mkdir(generatedDir, { recursive: true });

// 1. 内嵌 elkjs worker 源码（浏览器端没有 node:fs，只能由宿主注入字符串）。
const elkWorkerPath = nodeRequire.resolve('elkjs/lib/elk-worker.min.js');
const elkWorkerSrc = await readFile(elkWorkerPath, 'utf8');
await writeFile(
  join(generatedDir, 'elk-worker-source.ts'),
  `// GENERATED by scripts/build-demo.ts — do not edit.\nexport const ELK_WORKER_SOURCE: string = ${JSON.stringify(elkWorkerSrc)};\n`,
);

// 2. fixture 注册表：fixtures/*.json → 内嵌 import 列表。编号有 100+，按数字前缀自然排序。
const fixtureDir = join(root, 'fixtures');
const ids = (await readdir(fixtureDir))
  .filter((f) => f.endsWith('.json'))
  .map((f) => f.slice(0, -'.json'.length))
  .sort((a, b) => {
    const na = Number.parseInt(a, 10);
    const nb = Number.parseInt(b, 10);
    return (Number.isNaN(na) ? 9999 : na) - (Number.isNaN(nb) ? 9999 : nb) || a.localeCompare(b);
  });

const imports = ids.map((id, i) => `import f${i} from '../../fixtures/${id}.json';`).join('\n');
const entries = ids.map((id, i) => `  { id: '${id}', json: f${i} },`).join('\n');
await writeFile(
  join(generatedDir, 'fixtures.ts'),
  `// GENERATED by scripts/build-demo.ts — do not edit.\n${imports}\n\nexport interface DemoFixture {\n  id: string;\n  json: unknown;\n}\n\nexport const FIXTURES: DemoFixture[] = [\n${entries}\n];\n`,
);

// 3. 打包浏览器 bundle。
const build = await Bun.build({
  entrypoints: [join(root, 'demo', 'main.ts')],
  outdir: distDir,
  target: 'browser',
  minify: true,
});
if (!build.success) {
  console.error(build.logs);
  process.exit(1);
}

// 4. 静态资产：页面骨架、样式、bpmn-js 的 css（Viewer 渲染 marker/连线样式需要）。
await cp(join(root, 'demo', 'index.html'), join(distDir, 'index.html'));
await cp(join(root, 'demo', 'style.css'), join(distDir, 'style.css'));
await cp(
  join(root, 'node_modules', 'bpmn-js', 'dist', 'assets'),
  join(distDir, 'assets'),
  { recursive: true },
);

console.log(`demo built: demo/dist (${ids.length} fixtures, main.js bundles src + elkjs + bpmn-js)`);
